### ISSUE TITLE
Requiring srcdir != builddir worse than requiring srcdir == builddir

### ISSUE THREAD

**Issue by mathstuf** [cgwalters/build-api#1]
What's the rationale here? I've always found forced in-source builds to be the more annoying ones…

**Comment by cgwalters** [comment]
It's required to _support_ srcdir != builddir, or to annotate that you don't support it, hence forcing builders to copy the srcdir per build.  But it _is_ okay to do both.  Does that address your concern?

**Comment by mathstuf** [comment]
Ah, OK. Based on this:

```
buildapi-variable-no-builddir: Declares that this project only works when srcdir == builddir.

buildapi-variable-require-builddir: Declares that this project ONLY works when srcdir != builddir. Avoid this if you can.
```

it appeared as if one was worse than the other. Both of these should have "Avoid this if you can" flags then?

**Comment by cgwalters** [comment]
In https://github.com/cgwalters/build-api/pull/2, reply "@ cgwalters-bot r+" to approve, with no space between the "@" and name.  For more Homu usage instructions see http://escher.verbum.org:54856/
